import 'dotenv/config';
type Environment = NodeJS.ProcessEnv | Record<string, string | undefined>;
export declare function createEnv(environment: Environment): {
    DATABASE_URL: string;
    JWT_SECRET: string;
    GEMINI_API_KEY: string;
    INVITE_CODE: string;
    PORT: number;
    GEMINI_TIMEOUT_MS: number;
    GEMINI_MAX_ATTEMPTS: number;
    TRUST_PROXY_HOPS: number;
    CORS_ALLOWED_ORIGINS: string[];
    REQUEST_TIMEOUT_MS: number;
    SHUTDOWN_TIMEOUT_MS: number;
    SIMILARITY_CONFIDENCE_THRESHOLD: number;
    DANFE_MAX_ITEMS: number;
    GEMINI_ENABLED: boolean;
    GEMINI_GLOBAL_REQUESTS_PER_DAY: number;
    GEMINI_USER_REQUESTS_PER_DAY: number;
};
export declare const env: {
    DATABASE_URL: string;
    JWT_SECRET: string;
    GEMINI_API_KEY: string;
    INVITE_CODE: string;
    PORT: number;
    GEMINI_TIMEOUT_MS: number;
    GEMINI_MAX_ATTEMPTS: number;
    TRUST_PROXY_HOPS: number;
    CORS_ALLOWED_ORIGINS: string[];
    REQUEST_TIMEOUT_MS: number;
    SHUTDOWN_TIMEOUT_MS: number;
    SIMILARITY_CONFIDENCE_THRESHOLD: number;
    DANFE_MAX_ITEMS: number;
    GEMINI_ENABLED: boolean;
    GEMINI_GLOBAL_REQUESTS_PER_DAY: number;
    GEMINI_USER_REQUESTS_PER_DAY: number;
};
export {};
//# sourceMappingURL=env.d.ts.map